/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Bean.Mensagem;
import Bean.Usuario;
import Model.MensagemModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Jamilly
 */
public class CaixaEntradaSaida extends javax.swing.JFrame {
    private MensagemTableModel tbModel;
    private int op; //entrada == 0, saída == 1 ou lixeira == 2
    private Usuario user;
    /**
     * Creates new form CaixaEntradaSaida
     */
    public CaixaEntradaSaida(Usuario user, int op) {
        initComponents();
        this.user = user;
        this.op = op;
        tbModel = new MensagemTableModel();
        tbMensagem.setModel(tbModel);
        
        if(op == 0){
            tbModel.carregarDadosEntrada(user);
        }
        
        if(op == 1){
            tbModel.carregarDadosSaida(user);
            caixaLabel.setText("Caixa de Entrada");
            caixaALabel.setText("Caixa de Saída");
            lixeiraLabel.setVisible(false);
            Novo.setVisible(false);
        }
        if(op == 2){
            abrir.setText("Restaurar");
            lixeiraLabel.setVisible(false);
            caixaALabel.setText("Lixeira");
            caixaLabel.setText("Caixa de Entrada");
            Novo.setVisible(false);
            tbModel.carregarLixeira(user);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        logout = new javax.swing.JLabel();
        caixaLabel = new javax.swing.JLabel();
        lixeiraLabel = new javax.swing.JLabel();
        Novo = new javax.swing.JLabel();
        caixaALabel = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbMensagem = new javax.swing.JTable();
        voltar = new javax.swing.JButton();
        abrir = new javax.swing.JButton();
        excluir = new javax.swing.JButton();

        jButton2.setFont(new java.awt.Font("Baskerville Old Face", 1, 15)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 102, 0));
        jButton2.setText("Voltar");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setForeground(new java.awt.Color(0, 51, 102));

        jPanel2.setBackground(new java.awt.Color(240, 240, 241));

        jPanel9.setBackground(new java.awt.Color(0, 102, 0));
        jPanel9.setForeground(new java.awt.Color(255, 255, 255));

        logout.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("log out");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });

        caixaLabel.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        caixaLabel.setForeground(new java.awt.Color(255, 255, 255));
        caixaLabel.setText("Caixa de saída");
        caixaLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                caixaLabelMouseClicked(evt);
            }
        });

        lixeiraLabel.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        lixeiraLabel.setForeground(new java.awt.Color(255, 255, 255));
        lixeiraLabel.setText("Lixeira");
        lixeiraLabel.setToolTipText("");
        lixeiraLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lixeiraLabelMouseClicked(evt);
            }
        });

        Novo.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        Novo.setForeground(new java.awt.Color(255, 255, 255));
        Novo.setText("+ Novo");
        Novo.setToolTipText("");
        Novo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NovoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(caixaLabel)
                .addGap(89, 89, 89)
                .addComponent(lixeiraLabel)
                .addGap(101, 101, 101)
                .addComponent(Novo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(logout)
                .addGap(40, 40, 40))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logout)
                    .addComponent(Novo)
                    .addComponent(lixeiraLabel)
                    .addComponent(caixaLabel))
                .addGap(0, 4, Short.MAX_VALUE))
        );

        caixaALabel.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        caixaALabel.setForeground(new java.awt.Color(0, 102, 0));
        caixaALabel.setText("Caixa de entrada");

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Gill Sans MT", 1, 26)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 0));
        jLabel11.setText("Mapeia ME");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(caixaALabel)
                .addGap(213, 213, 213))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(caixaALabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tbMensagem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane1.setViewportView(tbMensagem);

        voltar.setFont(new java.awt.Font("Gill Sans MT", 1, 13)); // NOI18N
        voltar.setForeground(new java.awt.Color(0, 102, 0));
        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });

        abrir.setFont(new java.awt.Font("Gill Sans MT", 1, 13)); // NOI18N
        abrir.setForeground(new java.awt.Color(0, 102, 0));
        abrir.setText("Abrir Mensagem");
        abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirActionPerformed(evt);
            }
        });

        excluir.setFont(new java.awt.Font("Gill Sans MT", 1, 13)); // NOI18N
        excluir.setForeground(new java.awt.Color(0, 102, 0));
        excluir.setText("Excluir Mensagem");
        excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(abrir, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(voltar)
                    .addComponent(abrir)
                    .addComponent(excluir))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        int RUSure = JOptionPane.showConfirmDialog(this,"Tem certeza que deseja sair? "                    
                    , "", JOptionPane.YES_NO_OPTION);
        
        if (RUSure == 0){
            setVisible(false);
            Login l =  new Login();
            l.setVisible(true);
        }
    }//GEN-LAST:event_logoutMouseClicked

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        setVisible(false);
        if(op == 0){//entrada
            Cidades c = new Cidades(user);
            c.setVisible(true);
        }if(op == 1 || op == 2){//saida e lixeira
            CaixaEntradaSaida c = new CaixaEntradaSaida(user, 0);
            c.setVisible(true);
        }
    }//GEN-LAST:event_voltarActionPerformed

    private void caixaLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_caixaLabelMouseClicked
        setVisible(false);
        if(op == 0){//entrada
            CaixaEntradaSaida c = new CaixaEntradaSaida(user, 1);
            c.setVisible(true);
        }if(op == 1 || op == 2){//saida e lixeira
            CaixaEntradaSaida c = new CaixaEntradaSaida(user, 0);
            c.setVisible(true);
        }
    }//GEN-LAST:event_caixaLabelMouseClicked

    private void excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirActionPerformed
        if (tbMensagem.getSelectedRowCount() != 0){    
            if(op == 1){//saida
                int RUSure = JOptionPane.showConfirmDialog(this,"A mensagem será excluida permanentemente\n Tem certeza que deseja apagar? "                    
                        , "", JOptionPane.YES_NO_OPTION);
                if (RUSure == 0){
                    Mensagem msg = tbModel.getMensagem(tbMensagem.getSelectedRow());
                    MensagemModel model = new MensagemModel();
                    model.apagaMensagem(msg, 1, 0); //msg, viewdest, viewrem
                    tbModel.carregarDadosEntrada(user);            
                }
            }if(op == 2){//lixeira
                int RUSure = JOptionPane.showConfirmDialog(this, "A mensagem será excluida permanentemente\n Tem certeza que deseja apagar? "                   
                        , "", JOptionPane.YES_NO_OPTION);
                if (RUSure == 0){
                    Mensagem msg = tbModel.getMensagem(tbMensagem.getSelectedRow());
                    MensagemModel model = new MensagemModel();
                    model.apagaMensagem(msg, 2, 1);
                    tbModel.carregarLixeira(user);
                }
            } if(op == 0){//entrada
                Mensagem msg = tbModel.getMensagem(tbMensagem.getSelectedRow());
                MensagemModel model = new MensagemModel();
                model.apagaMensagem(msg, 0, 1);
                tbModel.carregarDadosEntrada(user);     
            }
        }else{
            JOptionPane.showMessageDialog(this, "Selecione uma mensagem");
        }
    }//GEN-LAST:event_excluirActionPerformed

    private void NovoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NovoMouseClicked
        NovaMensagem nova = new NovaMensagem(user,0);
        nova.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_NovoMouseClicked

    private void abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirActionPerformed
        if (tbMensagem.getSelectedRowCount() != 0){
            Mensagem msg = tbModel.getMensagem(tbMensagem.getSelectedRow());
            if(op == 0){//caixa de entrada
                VisualizaMensagem visu = new VisualizaMensagem(user, msg, 0);
                visu.setVisible(true);
                setVisible(false);
            }if(op == 1){//caixa de saida
                VisualizaMensagem visu = new VisualizaMensagem(user, msg, 1);
                visu.setVisible(true);
                setVisible(false);
            }
            if(op == 2){ //lixeira
                MensagemModel model = new MensagemModel();
                model.apagaMensagem(msg, 1, 1);
                tbModel.carregarLixeira(user);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Selecione uma mensagem");
        }
    }//GEN-LAST:event_abrirActionPerformed

    private void lixeiraLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lixeiraLabelMouseClicked
        CaixaEntradaSaida l = new CaixaEntradaSaida(user, 2);
        setVisible(false);
        l.setVisible(true);
    }//GEN-LAST:event_lixeiraLabelMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Novo;
    private javax.swing.JButton abrir;
    private javax.swing.JLabel caixaALabel;
    private javax.swing.JLabel caixaLabel;
    private javax.swing.JButton excluir;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lixeiraLabel;
    private javax.swing.JLabel logout;
    private javax.swing.JTable tbMensagem;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
